const Contents = {
  translation: {
    "Books and Publications": "Books and Publications",
    "The Books of Alice A. Bailey": "The Books of Alice A. Bailey",
    "Book Info": "This online app contains a searchable index of the 24 books of Alice A. Bailey and is offered free to the public in hopes that it will support the widest distribution and availability of this important body of work. The Lucis Publishing Companies offer paid versions of this app for desktop and mobile which include additional display options for easier browsing, the facility to take notes and bookmark pages, and a more advanced search function.",
    "Book Info 2": "We recommend the paid version for those doing advanced research of the books. The publishing companies are registered non-profit charities in the US and UK. All proceeds support the wider distribution of the work of Alice A. Bailey and the Tibetan.",
    "Click here to get the link for Paid Version.":"Click here to get the link for Paid Version.",
    "Browse All": "Browse All",
    "Compilation": "Compilation",
    "Search word or phrase" : "Search word or phrase",
    "Lucis Trust" : "Lucis Trust",
    "Read Now" : "Read Now",
    "Buy Now" : "Buy Now",
    "Please enter a search term":"Please enter a search term",
    "Please select at least one book":"Please select at least one book",
    "Search":"Search",
    "Search Options":"Search Options",
    "By" : "By",
    "Back" : "Back",
    "Next Section" : "Next Section",
    "Previous Section" : "Previous Section",
    "in this Section" : "in this Section",
    "in next Section" : "in next Section",
    "Copyright 2023. All Rights Reserved." : "Copyright 2023. All Rights Reserved.",
    "of" : "of",
    "Search by" : "Search by",
    "Exact Match" : "Exact Match",
    "Select Books" : "Select Books",
    "Select All" : "Select All",
    "Approximate Match" : "Approximate Match",
    "UnSelect All" : "UnSelect All",
    "Prev Result": "Prev Result",
    "Next Result": "Next Result",
    "No Results Found": "No Results Found",
    "Current Book Result" : "Current Book Result",
    "Total Results" : "Total Results",
    "Please Search for Something": "Please Search for Something",
    "Searching...": "Searching...",
    "No Book Opened with Results": "No Book Opened with Results",
    "Readers": "Readers",
    "Completed": "Completed",
    "PageNumberTooltip":"This pagination adapts to the size of the display. Page numbers matching the print edition of the books are included within the text.",
    "helpText": "To use this search function, type a keyword or phrase and select title(s) from the dropdown. Consider subscribing to the paid version of the app to expand the search beyond exact matches to your phrase.",
    "Premium Apps" : "Premium Apps",
    "Lucis Publishing Company Book Store": "Lucis Publishing Company Book Store",
    "Read more": "Read more",
    "Read less": "Read less",
    "Collapse Sidebar": "Collapse Sidebar",
    "Expand Sidebar": "Expand Sidebar",
    "Expand Search Results": "Expand Search Results",
    "Collapse Search Results": "Collapse Search Results",
  }
};

export default Contents;
