const Contents = {
  translation: {
    "Books and Publications": "Livres et publications",
    "The Books of Alice A. Bailey": "Les livres d'Alice A. Bailey",
    "Book Info": "Cette application en ligne contient un index consultable des 24 livres d'Alice A. Bailey et est offerte gratuitement au public dans l'espoir qu'elle soutiendra la distribution et la disponibilité la plus large possible de cet important corpus d'œuvres. Les sociétés d'édition Lucis proposent des versions payantes de cette application pour ordinateur et mobile qui incluent des options d'affichage supplémentaires pour une navigation plus facile, la possibilité de prendre des notes et de marquer des pages, ainsi qu'une fonction de recherche plus avancée.",
    "Book Info 2": "Nous recommandons la version payante à ceux qui effectuent des recherches avancées sur les livres. Les sociétés d'édition sont des organisations caritatives à but non lucratif enregistrées aux États-Unis et au Royaume-Uni. Tous les profits soutiennent la diffusion plus large du travail d'Alice A. Bailey et du Tibétain.",
    "Click here to get the link for Paid Version.":"Cliquez ici pour obtenir le lien vers la version payante.",
    "Browse All": "Parcourir tout",
    "Compilation": "Compilation",
    "Search word or phrase" : "Rechercher un mot ou une expression",
    "Lucis Trust" : "Lucis Trust",
    "Read Now" : "Lisez maintenant",
    "Buy Now" : "Acheter maintenant",
    "Please enter a search term":"Veuillez saisir un terme de recherche",
    "Please select at least one book":"Veuillez sélectionner au moins un livre",
    "Search":"Recherche",
    "Search Options":"Options de recherche",
    "By" : "Par",
    "Back" : "Dos",
    "Next Section" : "Section suivante",
    "Previous Section" : "Section précédente",
    "in this Section" : "dans cette section",
    "in next Section" : "dans la section suivante",
    "Copyright 2023. All Rights Reserved." : "droits d'auteur 2023. Tous droits réservés.",
    "of" : "de",
    "Select Books" : "Sélectionnez les livres",
    "Select All" : "Tout sélectionner",
    "Approximate Match" : "Correspondance approximative",
    "UnSelect All" : "Tout déselectionner",
    "Exact Match" : "Correspondance exacte",
    "Search by" : "Rechercher par",
    "No Results Found": "Aucun résultat trouvé",
    "Current Book Result" : "Résultat du livre actuel",
    "Total Results" : "Résultats totaux",
    "Prev Result": "Résultat précédent",
    "Next Result": "Résultat suivant",
    "Please Search for Something": "Veuillez rechercher quelque chose",
    "Searching...": "Recherche en cours...",
    "No Book Opened with Results": "Aucun livre ouvert avec des résultats",
    "Readers": "Lecteurs",
    "Completed": "Terminé",
      "PageNumberTooltip":"Cette pagination s'adapte à la taille de l'affichage. Les numéros de page correspondant à l'édition imprimée des livres sont inclus dans le texte.",
      "helpText": "Pour utiliser cette fonction de recherche, saisissez un mot-clé ou une expression et sélectionnez le(s) titre(s) dans la liste déroulante. Pensez à vous abonner à la version payante de l'application pour étendre la recherche au-delà des correspondances exactes à votre expression.",
      "Premium Apps" : "Applications Premium",
      "Lucis Publishing Company Book Store": "Librairie de la société d'édition Lucis",
      "Read more": "Lire la suite",
    "Read less": "Lire moins",
    "Collapse Sidebar": "Réduire la barre latérale",
    "Expand Sidebar": "Développer la barre latérale",
    "Expand Search Results": "Développer les résultats de la recherche",
    "Collapse Search Results": "Réduire les résultats de la recherche",
    "Premium": "Prime",
    "Books":"Livres",
    "Compilations":"Compilations",
    "The Consciousness":"La conscience",
    "Home":"Maison",
    "Annotations":"Annotations",
    "Help":"Aide",
    "About":"À propos",
    "Logout":"Se déconnecter",
    "Your Progress":"Votre progression",
    "Sort by:" :"Trier par:",
    "Recently Opened":"Récemment ouvert",
    "Favorite":"Préférée",
    "A-Z":"A à Z",
    "Z-A":"Z-A"
  }
};

export default Contents;
